version: '3'
services:
  app:
    image: soroushbeigi/naji:latest
    depends_on:
      - db
    ports:
      - "9876:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: 123456
      DB_NAME: naji_db

  db:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: naji_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
